# Generated by Django 5.1.1 on 2025-10-05 18:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(help_text='Our World in Data, JHU CSSE, WHO', max_length=255, verbose_name='Nom de la source')),
                ('source_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de la source')),
                ('source_type', models.CharField(blank=True, choices=[('official', 'Official'), ('academic', 'Academic'), ('aggregator', 'Aggregator')], max_length=50, null=True, verbose_name='Type de source')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Source de données',
                'verbose_name_plural': 'Sources de données',
                'db_table': 'sources',
                'ordering': ['source_name'],
            },
        ),
        migrations.CreateModel(
            name='Pandemic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pandemic_name', models.CharField(max_length=100, verbose_name='Nom de la pandémie')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, help_text='NULL si pandémie active', null=True, verbose_name='Date de fin')),
                ('pandemic_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('pathogene_agent', models.CharField(blank=True, choices=[('virus', 'Virus'), ('bacteria', 'Bacteria'), ('fungi', 'Fungi'), ('parasite', 'Parasite')], max_length=50, null=True, verbose_name='Agent pathogène')),
                ('who_classification', models.CharField(blank=True, choices=[('pandemic', 'Pandemic'), ('epidemic', 'Epidemic'), ('outbreak', 'Outbreak')], max_length=50, null=True, verbose_name='Classification WHO')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Pandémie',
                'verbose_name_plural': 'Pandémies',
                'db_table': 'pandemics',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, verbose_name='Nom du fichier')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'import")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='msp_backend.datasource', verbose_name='Source de données')),
            ],
            options={
                'verbose_name': 'Fichier de données',
                'verbose_name_plural': 'Fichiers de données',
                'db_table': 'files',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=50, verbose_name='Continent')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('province_state', models.CharField(blank=True, help_text='Subdivision administrative si disponible', max_length=100, null=True, verbose_name='Province/État')),
                ('admin2_USA', models.CharField(blank=True, max_length=50, null=True, verbose_name='Admin2 USA')),
                ('iso_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Code ISO')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Coordonnées GPS précises', max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Coordonnées GPS précises', max_digits=11, null=True, verbose_name='Longitude')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='Population')),
                ('who_region', models.CharField(blank=True, max_length=50, null=True, verbose_name='Région WHO')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Localisation',
                'verbose_name_plural': 'Localisations',
                'db_table': 'locations',
                'indexes': [models.Index(fields=['country', 'province_state'], name='idx_location_hierarchy'), models.Index(fields=['who_region'], name='idx_who_region')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('iso_code__isnull', False)), fields=('iso_code',), name='idx_iso_code')],
            },
        ),
        migrations.CreateModel(
            name='PandemicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(verbose_name="Date d'observation")),
                ('total_cases', models.PositiveIntegerField(default=0, verbose_name='Cas cumulés confirmés')),
                ('new_cases', models.PositiveIntegerField(default=0, verbose_name='Nouveaux cas quotidiens')),
                ('total_deaths', models.PositiveIntegerField(default=0, verbose_name='Décès cumulés')),
                ('new_deaths', models.PositiveIntegerField(default=0, verbose_name='Nouveaux décès quotidiens')),
                ('total_recovered', models.PositiveIntegerField(blank=True, help_text='Peut être NULL si pas rapporté', null=True, verbose_name='Total guérisons')),
                ('active_cases', models.PositiveIntegerField(blank=True, help_text='Calculé ou rapporté selon source', null=True, verbose_name='Cas actifs')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='data_records', to='msp_backend.datafile', verbose_name='Fichier source')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pandemic_data', to='msp_backend.location', verbose_name='Localisation')),
                ('pandemic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='data_points', to='msp_backend.pandemic', verbose_name='Pandémie')),
            ],
            options={
                'verbose_name': 'Donnée de pandémie',
                'verbose_name_plural': 'Données de pandémies',
                'db_table': 'pandemics_data',
                'ordering': ['-observation_date', 'location__country'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_function', models.CharField(blank=True, max_length=100, null=True, verbose_name='Function')),
                ('user_organization', models.CharField(blank=True, help_text='Organization or company where the user works', max_length=100, null=True, verbose_name='Organization')),
                ('last_connection', models.DateTimeField(blank=True, null=True, verbose_name='Last connection')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='datafile',
            index=models.Index(fields=['source'], name='idx_source_tracking'),
        ),
        migrations.AddIndex(
            model_name='datafile',
            index=models.Index(fields=['user'], name='idx_user_files'),
        ),
        migrations.AddIndex(
            model_name='pandemicdata',
            index=models.Index(fields=['observation_date'], name='idx_time_series'),
        ),
        migrations.AddIndex(
            model_name='pandemicdata',
            index=models.Index(fields=['file'], name='idx_file_tracking'),
        ),
        migrations.AddConstraint(
            model_name='pandemicdata',
            constraint=models.UniqueConstraint(fields=('pandemic', 'location', 'observation_date'), name='idx_unique_observation'),
        ),
    ]
