# Generated by Django 5.1.1 on 2025-10-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msp_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='admin2_usa',
        ),
        migrations.RemoveField(
            model_name='location',
            name='continent',
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='location',
            name='who_region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Région WHO'),
        ),
    ]
