# Generated by Django 5.1.1 on 2025-10-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msp_backend', '0002_remove_location_admin2_usa_remove_location_continent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandemicdata',
            name='incident_rate',
            field=models.FloatField(blank=True, help_text='Nombre de nouveaux cas pour .... dhabitants', null=True, verbose_name="Taux d'incidence"),
        ),
        migrations.AddIndex(
            model_name='pandemicdata',
            index=models.Index(fields=['total_cases'], name='idx_total_cases'),
        ),
        migrations.AddIndex(
            model_name='pandemicdata',
            index=models.Index(fields=['total_deaths'], name='idx_total_deaths'),
        ),
        migrations.AddIndex(
            model_name='pandemicdata',
            index=models.Index(fields=['incident_rate'], name='idx_incident_rate'),
        ),
    ]
